version: "3"
services:
  app:
    build: .
    tty: true
    stdin_open: true
    working_dir: /var/www
    platform: linux/amd64
    ports:
        - "3000:3000"
    volumes:
        - ./:/var/www
volumes:
    db: